Repository Shreya111111/Linkscrape, pull requests merged in 2023-12, with the labels that each got.

#11 Implemented filtering and sorting feature
  myenv/pyvenv.cfg
  myproject/db.sqlite3
  myproject/myapp/__pycache__/__init__.cpython-311.pyc
  myproject/myapp/__pycache__/admin.cpython-311.pyc
  myproject/myapp/__pycache__/apps.cpython-311.pyc
  myproject/myapp/__pycache__/models.cpython-311.pyc
  myproject/myapp/__pycache__/views.cpython-311.pyc
  myproject/myapp/migrations/0002_link_time.py
  myproject/myapp/migrations/__pycache__/0001_initial.cpython-311.pyc
  myproject/myapp/migrations/__pycache__/0002_link_time.cpython-311.pyc
  myproject/myapp/migrations/__pycache__/__init__.cpython-311.pyc
  myproject/myapp/models.py
  myproject/myapp/templates/myapp/result.html
  myproject/myapp/views.py
  myproject/myproject/__pycache__/__init__.cpython-311.pyc
  myproject/myproject/__pycache__/settings.cpython-311.pyc
  myproject/myproject/__pycache__/urls.cpython-311.pyc
  myproject/myproject/__pycache__/wsgi.cpython-311.pyc
Labels: enhancement, django, Codepeak23

#12 Recommended UI improvements done
  myproject/db.sqlite3
  myproject/myapp/__pycache__/models.cpython-311.pyc
  myproject/myapp/__pycache__/views.cpython-311.pyc
  myproject/myapp/migrations/__pycache__/0002_link_time.cpython-311.pyc
  myproject/myapp/templates/myapp/result.html
  myproject/myproject/__pycache__/settings.cpython-311.pyc
Labels: enhancement, Codepeak23

#14 added export functionality for csv, json and excel
  myproject/db.sqlite3
  myproject/myapp/__pycache__/__init__.cpython-310.pyc
  myproject/myapp/__pycache__/admin.cpython-310.pyc
  myproject/myapp/__pycache__/apps.cpython-310.pyc
  myproject/myapp/__pycache__/models.cpython-310.pyc
  myproject/myapp/__pycache__/views.cpython-310.pyc
  myproject/myapp/migrations/__pycache__/0001_initial.cpython-310.pyc
  myproject/myapp/migrations/__pycache__/0002_link_time.cpython-310.pyc
  myproject/myapp/migrations/__pycache__/__init__.cpython-310.pyc
  myproject/myapp/templates/myapp/result.html
  myproject/myapp/views.py
  myproject/myproject/__pycache__/__init__.cpython-310.pyc
  myproject/myproject/__pycache__/settings.cpython-310.pyc
  myproject/myproject/__pycache__/urls.cpython-310.pyc
  myproject/myproject/__pycache__/wsgi.cpython-310.pyc
  myproject/myproject/urls.py
Labels: django, Codepeak23
